[package]
name = "uniffi-bindgen"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
uniffi = { workspace = true, features = ["cli"] }
