[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
crux_core.workspace = true
serde = { workspace = true, features = ["derive"] }
once_cell = "1"
uniffi = "0.28"
wasm-bindgen = "0.2"
matrix-sdk = "0.7"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.28", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.28", features = ["build"] }
